"""Beat detection, BPM estimation, and phrase tracking.

Consumes the per-frame ``_onset`` signal (mean band energy) produced by
:class:`~server.audio.analyzer.SpectrumAnalyzer` and derives:

* ``beat``      – a boolean pulse fired on detected onsets
* ``bpm``       – tempo estimated from the onset envelope autocorrelation
* ``phrase``    – beat count within the current musical phrase
* ``transition``– a 0..1 score predicting how close we are to a mix point

The detector keeps a rolling onset envelope (~10 s) and re-estimates BPM a
few times per second. Beat pulses are generated by adaptive thresholding of
the onset signal with a refractory period derived from the current BPM.
"""

from __future__ import annotations

from collections import deque

import numpy as np

# BPM search range.
MIN_BPM = 70.0
MAX_BPM = 200.0

# Onset envelope history length in seconds.
ENVELOPE_SECONDS = 10.0

# How often (seconds) to re-run the BPM autocorrelation.
BPM_REESTIMATE_INTERVAL = 0.5

# Minimum gap between beats as a fraction of the beat period.
REFRACTORY_FRACTION = 0.55


class BeatDetector:
    """Adaptive onset/beat detector with BPM and phrase tracking."""

    def __init__(
        self,
        sample_rate: int = 44100,
        frame_rate: float = 60.0,
        phrase_length: int = 32,
    ):
        self.frame_rate = frame_rate
        self.phrase_length = phrase_length

        envelope_len = int(ENVELOPE_SECONDS * frame_rate)
        self._envelope: deque[float] = deque(maxlen=envelope_len)
        self._prev_onset = 0.0
        self._running_mean = 0.0

        self.bpm = 120.0
        self._last_bpm_time = 0.0

        # Virtual clock advanced by 1/frame_rate each update(). Using the
        # frame cadence (not wall-clock) keeps beat timing deterministic and
        # immune to scheduler jitter.
        self._time = 0.0
        self._dt = 1.0 / frame_rate

        # Negative so the first onset is not suppressed by the refractory gate.
        self._last_beat_time = -10.0
        self._beat_count = 0
        self._phrase_beat = 0

        # Transition scoring state.
        self._energy_history: deque[float] = deque(maxlen=int(frame_rate * 4))

    def reset(self) -> None:
        self._envelope.clear()
        self._prev_onset = 0.0
        self._running_mean = 0.0
        self._time = 0.0
        self._last_beat_time = -10.0
        self._beat_count = 0
        self._phrase_beat = 0
        self._energy_history.clear()

    def update(self, onset: float, energy: float) -> dict:
        """Advance the detector by one analysis frame.

        Returns ``{beat, bpm, phraseProgress, phraseLength, transition}``.
        """
        self._time += self._dt
        now = self._time

        # Spectral flux: positive change in onset energy.
        flux = max(0.0, onset - self._prev_onset)
        self._prev_onset = onset
        self._envelope.append(flux)

        # Adaptive threshold = running mean of flux.
        self._running_mean = self._running_mean * 0.98 + flux * 0.02
        threshold = self._running_mean * 1.6 + 0.005

        beat = False
        beat_period = 60.0 / self.bpm if self.bpm > 0 else 0.5
        refractory = beat_period * REFRACTORY_FRACTION
        if flux > threshold and (now - self._last_beat_time) >= refractory:
            beat = True
            self._last_beat_time = now
            self._beat_count += 1
            self._phrase_beat = (self._phrase_beat + 1) % self.phrase_length

        # Periodically re-estimate BPM from the envelope autocorrelation.
        if now - self._last_bpm_time >= BPM_REESTIMATE_INTERVAL:
            self._last_bpm_time = now
            estimated = self._estimate_bpm()
            if estimated:
                # Smooth toward the new estimate to avoid jitter.
                self.bpm = self.bpm * 0.7 + estimated * 0.3

        self._energy_history.append(energy)

        return {
            "beat": beat,
            "bpm": round(self.bpm, 1),
            "phraseProgress": self._phrase_beat,
            "phraseLength": self.phrase_length,
            "transition": self._transition_score(),
        }

    # -- internals ------------------------------------------------------

    def _estimate_bpm(self) -> float | None:
        if len(self._envelope) < int(self.frame_rate * 2):
            return None
        env = np.asarray(self._envelope, dtype=np.float32)
        env = env - np.mean(env)
        if np.max(np.abs(env)) < 1e-6:
            return None

        # Autocorrelation via FFT.
        n = len(env)
        fft = np.fft.rfft(env, n=2 * n)
        acf = np.fft.irfft(fft * np.conj(fft))[:n]
        if acf[0] <= 0:
            return None
        acf = acf / acf[0]

        # Convert BPM range to lag range (in frames).
        min_lag = int(self.frame_rate * 60.0 / MAX_BPM)
        max_lag = int(self.frame_rate * 60.0 / MIN_BPM)
        max_lag = min(max_lag, n - 1)
        if max_lag <= min_lag:
            return None

        search = acf[min_lag : max_lag + 1]
        if search.size == 0:
            return None
        best_lag = min_lag + int(np.argmax(search))
        if best_lag <= 0:
            return None
        return float(self.frame_rate * 60.0 / best_lag)

    def _transition_score(self) -> float:
        """Heuristic 0..1 score: high near phrase boundaries + energy dips."""
        if not self._energy_history:
            return 0.0
        # Phrase proximity: ramp up as we approach the end of the phrase.
        phrase_frac = self._phrase_beat / max(1, self.phrase_length)
        phrase_score = max(0.0, (phrase_frac - 0.75) / 0.25)

        # Energy dip: compare recent energy to the trailing average.
        history = np.asarray(self._energy_history, dtype=np.float32)
        if history.size < 4:
            return float(phrase_score * 0.5)
        recent = float(np.mean(history[-int(self.frame_rate):]))
        baseline = float(np.mean(history))
        dip = 0.0
        if baseline > 1e-4:
            dip = float(np.clip((baseline - recent) / baseline, 0.0, 1.0))

        return float(np.clip(0.6 * phrase_score + 0.4 * dip, 0.0, 1.0))
